// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RenoSystemDB.Entities;

public partial class Supply
{
    public int SupplyId { get; set; }

    public int JobId { get; set; }

    public string Material { get; set; }

    public int Quantity { get; set; }

    public decimal MaterialCost { get; set; }

    public virtual Job Job { get; set; }
}